runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /index.html
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/404.html
  upload: www/404.html
  secure: always
